# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database/track_order.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    restart: always
    ports:
      - 8080:80
    links:
      - db

  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    restart: always
    ports:
      - 80:80
    links:
      - db
      - api
